/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: 888e7401eb50a29ef499db42941d12b0)
interface __BaseEnv_Env {
	KV: KVNamespace;
	STORAGE: R2Bucket;
	DB: D1Database;
	IMAGES: ImagesBinding;
	SITE_URL: string;
	MAX_UPLOAD_BYTES: string;
	MAX_TTL_SECONDS: string;
	ALLOWED_MIME_TYPES: string;
	TEAM_DOMAIN: string;
	POLICY_AUD: string;
	ACCESS_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "MAX_UPLOAD_BYTES" | "MAX_TTL_SECONDS" | "ALLOWED_MIME_TYPES" | "TEAM_DOMAIN" | "POLICY_AUD" | "ACCESS_KEY">> {}
}
